title: Marco Estrella
markdown: kramdown
highlighter: rouge
exclude: ["LICENSE.txt", "README.md"]

future: true
baseurl: "http://jmarkstar.com"
#baseurl: ""
permalink: /:title/

owner:
  name: Marco Estrella Cardenas

social:
   linkedin: jmarkstar
   github: jmarkstar
   twitter: jmarkstar
#   facebook: mestrella1991
   email: mestrella.1991@gmail.com

google_analytics: "UA-65998111-1"

languages: ["es", "en"]

exclude_from_localizations: ["assets", "javascript"]

# Plugins
gems:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate
